on:
  push:
  schedule:
    - cron: 0 0 * * 1 # At 00:00 on Monday

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Install shards
        run: shards install

      - name: Check code format
        run: crystal tool format --check

      - name: Lint with ameba
        run: bin/ameba

  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {crystal: latest}
          - {crystal: 1.6}
          - {crystal: 1.5}
    name: Tests & Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
          shards: false

      - name: Run tests
        run: crystal spec
